# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('intro', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=15)),
            ],
        ),
    ]
